# Generated by Django 5.0.6 on 2024-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='character',
            field=models.IntegerField(choices=[(0, 'Yoda1'), (1, 'Yoda2'), (3, 'Yoda3'), (4, 'Yoda4'), (5, 'Yoda5')], default=0),
        ),
    ]
