# Generated by Django 5.0.6 on 2024-05-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_session_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='slug',
        ),
    ]
