# Generated by Django 5.0.6 on 2024-05-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_remove_session_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='level',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (3, 'Hard')], default=0),
        ),
    ]
