# Generated by Django 5.0.6 on 2024-05-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_name',
        ),
    ]
