# Generated by Django 5.0.6 on 2024-05-25 17:24

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_character_alter_session_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='med_one',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='med_1'),
        ),
        migrations.AddField(
            model_name='character',
            name='med_two',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='med_2'),
        ),
        migrations.AddField(
            model_name='character',
            name='meditation_one_name',
            field=models.CharField(default='Default Meditation Name1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='meditation_two_name',
            field=models.CharField(default='Default Meditation Name2', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='character',
            field=models.CharField(max_length=200),
        ),
    ]
