# Generated by Django 5.0.6 on 2024-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_character_med_one_character_med_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='medition_selected',
            field=models.CharField(default='Default older', max_length=200),
            preserve_default=False,
        ),
    ]
