# Generated by Django 5.0.6 on 2024-05-26 11:23

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoda_app', '0004_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
